openapi: 3.0.0
info:
  title: StudySync API
  version: 1.0.0
  description: A REST API for managing study topics using Flask and MongoDB.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /topics:
    get:
      summary: Get all topics
      responses:
        '200':
          description: A list of topics
    post:
      summary: Add a new topic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                subject:
                  type: string
                notes:
                  type: string
      responses:
        '201':
          description: Topic successfully added

  /topics/{id}:
    put:
      summary: Update a topic
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                subject:
                  type: string
                notes:
                  type: string
      responses:
        '200':
          description: Topic updated

    delete:
      summary: Delete a topic
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Topic deleted